### ISSUE TITLE
Change doco to explain NServiceBus related features for each endpoint

### ISSUE THREAD

**Issue by brunobertechini** [mauroservienti/shopper#45]
Hi Mauro, first of all, congrats on this sample as its providing better understanding of UI composition model.

May I ask you to update the doco to explain each endpoint (api host, mvc and angular client) in regards of nservicebus featres/configurations?

Things like: Using RavenDB for persistence, XXX for transport etc ?

I think this will clarify newcomers where to look at

Bruno

**Comment by brunobertechini** [comment]
I may help with this, if you'd like, to create a PR containing docos with my understantanding and you can point me to right approach.

Bruno

**Comment by mauroservienti** [comment]
Hi @brunobertechini first of all thanks. Yes, some help is definitely required here, there is a ~plan~ wish https://github.com/mauroservienti/shopper/issues/43 to write doco but as always time is never enough.

Actually I'm working hand in hand with Udi on a new design for UI Composition, so it might be interesting to wait till that effort is done (end of this week) so that I'll be able to bring that experience in here, and finally be able to write some doco and work on all ather pending issues.

**Comment by brunobertechini** [comment]
Hi Mauro, so long we have this chat...

Any news on the new UI composition techniques ?

Bruno
